all:
	gcc LinuxX11/Common/esShader.c \
		LinuxX11/Common/esTransform.c \
		LinuxX11/Common/esShapes.c \
		LinuxX11/Common/esUtil.c \
		gles_show_yuv2.c \
		-o gles_show_yuv2 -ILinuxX11/Common \
			-lGLESv2 -lEGL -lm -lX11
