######################################################################
# Automatically generated by qmake (3.0) ?? 8? 1 14:38:25 2016
######################################################################

TEMPLATE = app
TARGET = test1
INCLUDEPATH += .

# Input
SOURCES += main.cpp
