
all:
	g++ rectangle.c -o rectangle `pkg-config --cflags --libs cairo`
	gcc helloworld_pdf.c -o helloworld_pdf `pkg-config --cflags --libs cairo`
	g++ blurgauss0.c -o blurgauss0 `pkg-config --cflags --libs cairo`
