######################################################################
# Automatically generated by qmake (3.0) ?? 8? 1 14:40:48 2016
######################################################################

TEMPLATE = app
TARGET = test2
INCLUDEPATH += .

# Input
HEADERS += Window.h
SOURCES += main.cpp
