LOCAL_FILES += test_project1.cpp
LOCAL_BIN = test_project1

LDFLAGS += \
	-lgui \
	-legl \
	-lapp \
	-lgles \
	-lwaylandclient-priv \
	-lutils \
	-lGLESv2 \
	-lEGL \
	-lpthread \
	-lwayland-client \
	-lwayland-egl \
	-lglapi \
	-lpng \
